### ISSUE TITLE
Weird time serialization problems after importing 'expo-server-sdk-java'

### ISSUE THREAD

**Issue by brunoaduarte** [jav/expo-server-sdk-java#11]
I have i SpringBoot gradle project that i've imported 'expo-server-sdk-java'

`implementation 'io.github.jav:expo-server-sdk:0.7.0'`

Problem is that after this import i'm having weird behavior on Date serialization to json

Before
`2020-07-07T18:49:32.142+00:00`

After
`2020-07-07T18:49:32.142+0000`

Javascript doesn't recognize the latest as a valid date, so `new Date("2020-07-07T18:49:32.142+0000")` will return NaN

Probably there's some outdated or bugged dependency on this project.

**Comment by jav** [comment]
Would you mind sharing your projects dependencies so that I may compare with this projects dependencies versions?

**Comment by jav** [comment]
Hi!
Would you mind sharing your projects dependencies with versions so that I may compare with this projects dependencies versions?

**Comment by jav** [comment]
For what it's worth. In Firefox 78.0.1 `new Date("2020-07-07T18:49:32.142+0000")` returns `Date Tue Jul 07 2020 20:49:32 GMT+0200 (Central European Summer Time)`

**Comment by jav** [comment]
Which browser do you use?

**Comment by brunoaduarte** [comment]
> Hi!
> Would you mind sharing your projects dependencies with versions so that I may compare with this projects dependencies versions?

```
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.session:spring-session-core'
//	implementation 'io.github.jav:expo-server-sdk:0.7.0'
	compile group: 'org.modelmapper', name: 'modelmapper', version: '2.3.8'
	compile group: 'com.arangodb', name: 'arangodb-spring-data', version: '3.2.5'
	compile group: 'org.apache.commons', name: 'commons-collections4', version: '4.4'
	compile group: 'commons-io', name: 'commons-io', version: '2.7'	
	compile group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2'
	compile group: 'com.github.javafaker', name: 'javafaker', version: '1.0.2'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
}
```

**Comment by brunoaduarte** [comment]
> Which browser, browser-version and OS do you use?

It's a React Native Expo app...

**Comment by jav** [comment]
Haha! ofcourse it’s react native :)
I’m not sure what I was thinking :)

**Comment by jav** [comment]
Hi.

Sorry for the update latency.

Could you provide me with a code snippet where you generate a date in Java which I could try to use to reproduce?

Thank you

**Comment by jav** [comment]
Please reopen if this is still an issue and you're able to help me reproduce.
