### ISSUE TITLE
Exceptions should never be swallowed

### ISSUE THREAD

**Issue by celandro** [jav/expo-server-sdk-java#14]
Currently exceptions are swallowed and simply logged with a printStackTrace. This is not appropriate for a library.

All exceptions should be available on the ExpoTicket and all global exceptions available on a new root object

**Comment by jav** [comment]
I'm currently not able to sit down and review the PR. 
I'll be able to give feedback in about ~14 days 

In principle, I think it's an improvement.
Thank you!

**Comment by jav** [comment]
Hi!

Thank you for the ticket and the commit in the [commit](https://github.com/jav/expo-server-sdk-java/pull/13/commits/7fe6cb5d2630cb81ba1723028548ddbb7ecc6962)!

In reviewing [7fe6cb5](https://github.com/jav/expo-server-sdk-java/pull/13/commits/7fe6cb5d2630cb81ba1723028548ddbb7ecc6962) a few questions surged :)

If I understand you correctly, you want to add a possible state to "Status" that is "Exception".
Can you help me understand what type of exceptions you're thinking of?
The possible states for the PushReceipt 'status' field are either `ok` or an Error object (Push receipt errors)[https://docs.expo.io/push-notifications/sending-notifications/#push-receipt-errors] where the error Object may be one of  `DeviceNotRegistered`, `MessageTooBig`, `MessageRateExceeded`, `InvalidCredentials` and `InvalidProviderToken`.

[There are also a class of error where the entire request fails](https://docs.expo.io/push-notifications/sending-notifications/#push-receipts) where the client would recieve an `4xx` or `5xx` error which I haven't given much consideration yet.

The docs also state that "Expo couldn't deliver the message to the Android or iOS push notification service, the push receipt's details may also include service-specific information". Which I also have not given much thought :+1: 


In essence: 
What kind of errors are you looking to represent through the status `exception` and, if it diverges from the expo-server-sdk-node implementation, how do you suggest that we represent/document the divergence (for future maintainability)?

**Comment by celandro** [comment]
Some examples of an Exception would be a network exception, passing in
non-json serializable data objects and other things caught in the global
exception block. It basically means the request completely failed and
likely can be retried with correction. It would also be triggered if
someone killed a large batch process.  The old code simply swallowed the
exceptions which is not appropriate for production code. This is not for
errors at the individual message level, its for exceptions for the entire
batch of requests.

The changes I made were to address specific bugs I had. For example, i
uninstall and reinstall my dev app repeatedly and 90% of the expo tokens
were invalid so I wanted a way to easily remove them.

I saw a ticket regarding the same expo token issue in another repo and it
was responded to with a 'we should do that, but cant do it right now'

Perhaps the best approach is to talk with the implementers of the node
library and come up with a comprehensive approach for error handling that
will work for both platforms.

The other part of the patch regarding accepting POJOs and not just Maps I'm
pretty happy with except for the type signatures being a little messy.
What do you think?

**Comment by jav** [comment]
Resolved in 0.9.0
