### ISSUE TITLE
How can I know which message have failed ?

### ISSUE THREAD

**Issue by kopax** [jav/expo-server-sdk-java#18]
Hello, I would like to know if a token have failed to send the push notification so I can increase it's failure count.

```java
for (CompletableFuture<List<ExpoPushTicket>> messageReplyFuture : messageRepliesFutures) {
  try {
    for (ExpoPushTicket ticket : messageReplyFuture.get()) {
      allTickets.add(ticket);
    }
  } catch (InterruptedException e) {
    e.printStackTrace();
  } catch (ExecutionException e) {
    e.printStackTrace();
    expoPushTokenService.updateFailureCount(tokenId); // <--- I need to get the token here;
  }
}
```

How is it possible ? 

Thanks a lot!

**Comment by jav** [comment]
This is resolved in `0.9.0`.

Exceptions contain the messages (chunks) that where  to be sent.

See test [sendPushNotificationsReceiptAsyncThrowsExceptionWithAllFailedMessages](https://github.com/jav/expo-server-sdk-java/blob/master/src/test/java/io/github/jav/exposerversdk/PushClientTestCustomData.java#L400).
