### ISSUE TITLE
Entire request errors handling

### ISSUE THREAD

**Issue by rgmih** [jav/expo-server-sdk-java#24]
Hi @jav. Thanks a lot for this library!

There is a section in Expo's Push API about entire request errors processing, see https://docs.expo.io/push-notifications/sending-notifications/#request-errors. Expo server may response with non-200 status code and return HTTP-body with `errors` field in JSON. For example:

```
{
   "errors":[
      {
         "code":"PUSH_TOO_MANY_EXPERIENCE_IDS",
         "message":"All push notification messages in the same request must be for the same project; check the details field to investigate conflicting tokens.",
         "details":{
            "@username/projectAAA":[
               "ExponentPushToken[...]"
            ],
            "@username/projectBBB":[
               "ExponentPushToken[...]"
            ]
         }
      }
   ]
}
```

This part of API is not covered by current version of `expo-server-sdk-java` at all. Actually when processing `400 Bad Request` response from Expo server the library crashes with NPE at [PushClientCustomData.java:54](https://github.com/jav/expo-server-sdk-java/blob/9c96f1af203e5534debc3074177f13adc573708d/src/main/java/io/github/jav/exposerversdk/PushClientCustomData.java#L54) due to `data` json node is not found in future result.

There are two main problems to be solved:
- `DefaultPushServerResolver` is not handling exceptions correctly at [DefaultPushServerResolver.java#L31](https://github.com/jav/expo-server-sdk-java/blob/9c96f1af203e5534debc3074177f13adc573708d/src/main/java/io/github/jav/exposerversdk/helpers/DefaultPushServerResolver.java#L31) and [DefaultPushServerResolver.java#L43](https://github.com/jav/expo-server-sdk-java/blob/9c96f1af203e5534debc3074177f13adc573708d/src/main/java/io/github/jav/exposerversdk/helpers/DefaultPushServerResolver.java#L43): task is running in separate thread and throwing exceptions doesn't change result of `retCompletableFuture`. That's why in case of any error future always returns an empty string provided at [DefaultPushServerResolver.java#L47](https://github.com/jav/expo-server-sdk-java/blob/9c96f1af203e5534debc3074177f13adc573708d/src/main/java/io/github/jav/exposerversdk/helpers/DefaultPushServerResolver.java#L47).
- Server's response contained in `urlConnection.getErrorStream()` in case of `400 Bad Request` and other errors is not parsed at all because `IOException` is being thrown when trying to access `urlConnection.getInputStream()`. Meanwhile it may contain important information about entire request errors (see [API specification link](https://docs.expo.io/push-notifications/sending-notifications/#request-errors) attached above).

To address these problems I propose a patch containing following changes to library:
- `DefaultPushServerResolver` is rewriten to handle exceptions correctly and pass them to `retCompletableFuture`.
- In case of `IOException` in `DefaultPushServerResolver` the `urlConnection.getErrorStream()` is being parsed and corresponding response body is being returned as `retCompletableFuture` result.
- By the way I have removed invocation of `Executors.newCachedThreadPool()` on every request. Executor service instance is now a field of `DefaultPushServerResolver` class.
- `PushClientCustomData.sendPushNotificationsAsync` and `PushClientCustomData.getPushNotificationReceiptsAsync` are patched to process `errors` json field in response in addition to `data` field processing. In case `errors` field is found in response json it is parsed as a list of new `ExpoPushError` class instances and corresponding `PushNotificationException` or `PushNotificationReceiptsException` is being thrown. List of parsed errors as well as `data` content (ticket or receipt records) in that case are returned in underlying `PushNotificationErrorsException` / `PushNotificationReceiptsErrorsException` exceptions.

To be honest I don't really like provided aproach with wrapping `errors` and `data` in underlying exceptions but that's the only reasonable way I have found to return required data without changing `PushClient` (`sendPushNotificationsAsync` and `getPushNotificationReceiptsAsync`) public interface and keeping it backward-compatible with previous versions.

I have verified that handling `errors` in `sendPushNotificationsAsync` works as expected for now and `exception` in `PushNotificationException` being thrown contains `PushNotificationErrorsException` with correct errors data. We do not check Expo receipts in our app for a while so unfortunately I have not tested same changes to `getPushNotificationReceiptsAsync`.

Corresponding PR referencing this issue would be provided in a few minutes.

**Comment by jav** [comment]
How would you suggest to change the API to better accommodate for the change?

**Comment by jav** [comment]
Would you mind adding a few unit-tests?

**Comment by rgmih** [comment]
> How would you suggest to change the API to better accommodate for the change?

Well, possible solution is to change `sendPushNotificationsAsync` return type to a new `SendPushNotificationResponse` class of following structure:
```
public class SendPushNotificationsResponse {
    private final List<ExpoPushTicket> data;
    private final List<ExpoPushError> errors;

    public SendPushNotificationsResponse(List<ExpoPushTicket> data, List<ExpoPushError> errors) {
        this.data = data;
        this.errors = errors;
    }
    
    public List<ExpoPushTicket> getData() {
        return data;
    }

    public List<ExpoPushError> getErrors() {
        return errors;
    }
}
```
to represent any possible response Expo server may return.

> Would you mind adding a few unit-tests?

Sure. I'll try to add them to my PR in a day or two.

**Comment by jav** [comment]
I have thought of breaking the API.
I'd like to roll-up and hide the chunk calls such that `PushClient` has a `sendMessages()` method.
(rather than chunking a list, and the user having to manage a list of `CompletableFuture`.

That new method would do well to return a SendPushnotificationResponse (or similar), to encapsulate the complexities of multiple, in parallel, CompletableFutures.

That would create a migration path where we 
1. Incorporate your suggested changes.
2. mark the current `.sendPushNotificationsAsync` as deprecated  
3. Add a method `public SendPushMessagesResponse sendPushMessages( List<ExpoPushMessage> )` that implements what you just described.

**Comment by jav** [comment]
A prevous suggestion on the topic by another user:
https://github.com/jav/expo-server-sdk-java/pull/13/commits/399b9a642b73f11a68084c4bc67f9716f1389e07

**Comment by jav** [comment]
(thinking out loud)

The error modes are:
* When building PushMessages
    * Invalid token
        * Checked by `PushClient.isExponentPushToken()`
* Send PushMessage
    * Connection error when sending PushMessages `sendPushNotificationsAsync()`
        * Throws `PushNotificationException`
    * Response json mysteriously dosn't parse
        * Throws `PushNotificationException` with the messages that where expected to be part of the call
            * Need to verify if the exception is thrown correctly (it's thrown from inside a `CompletableFuture`)
    * HTTP error when sending PushMessages (managed by this patch)
        * Throws `PushNotificationErrorException` wrapped in a `PushNotificationException`
* Ticket errors
    * Provided by `PushClient.zipMessagesTickets()`
* Fetch receipts
    * Connection error when fetching receipts
        * Throws `PushNotificationReceiptsException`
    * Response json mysteriously dosn't parse
        * Throws `PushNotificationReceiptsException` with IDs that where expected to be part of the call
            * Need to verify if the exception is thrown correctly (it's thrown from inside a `CompletableFuture`)
    * Errors in specific receipts
        * Totally normal, represented in the `PushNotificationReceipt` class


Can you see any other error modes?

**Comment by rgmih** [comment]
Hello @jav, I have updated the PR with few unit tests.

>That would create a migration path...

Leaving old API method as deprecated and creating a new one accepting full list of messages with `CompletableFuture<SendPushMessagesResponse>` return type sounds good.

>Can you see any other error modes?

Not actually. Moreover I don't think it is required to split connection issues from parsing ones. I think it is enough to handle two cases: if valid response was received or not. In the first case it is enough to return `SendPushMessagesResponse` result without any exception so that user can manually check for `data` and `errors` fields in response. In the second case let's throw an exception containing list of source messages and underlying exception (IO-exception or Json-parse exception).

Anyway, I propose to leave complex API changes to some future release and build & publish an updated library version containing my latest patches on entire request errors processing. Hope to see patched release in common maven repo to avoid local dependency management. Thanks in advance!

**Comment by jav** [comment]
Merged.

I'm publishing version `1.1.0` now.

**Comment by rgmih** [comment]
@jav Hello again! It seems to me that there is no version `1.1.0` published. I can see only [here](https://search.maven.org/artifact/io.github.jav/expo-server-sdk) only `1.0.0` version published yesterday. It doesn't contain provided patches. Am I missing something?

I also have noticed that target jar (of version > 0.4.5) contains all dependencies class files including `com.fasterxml.jackson` and `org.apache.commons.lang3` packages. That's why resulting jar has 2.3Mb size. In comparison jar I have packages and installed locally from sources has 36Kb size. It seems to me that packaging jar with all dependencies is a bad practice. That may lead to dependency problems in runtime that are hard to debug (when multiple versions of same library are presented in a classpath). What is your opinion? What is that made for? Shall we fix it?

**Comment by jav** [comment]
Odd that `1.1.0` wasn't properly published. 
I'll try again.

I don't have a strong opinion on the trade-off between size and bundled dependencies.
I wouldn't decline a PR on the topic.

**Comment by jav** [comment]
`1.1.0`is published now.
