### ISSUE TITLE
Error by compiling my project with maven

### ISSUE THREAD

**Issue by emmanuel-D** [jav/expo-server-sdk-java#5]
I am using the version 0.5.4 in my pom.xml and when I compile my project with maven, I get the following errors:

`PushNotificationService.java:[7,35] cannot access io.github.jav.exposerversdk.ExpoPushMessage
[ERROR]   bad class file: /.m2/repository/io/github/jav/expo-server-sdk/0.4.1/expo-server-sdk-0.4.1.jar(io/github/jav/exposerversdk/ExpoPushMessage.class)`
`[ERROR]     class file has wrong version 55.0, should be 52.0`
`[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.`

I am using Spring Boot & Java 8 in my project.
     
     
     <dependency>
     <groupId>io.github.jav</groupId>
     <artifactId>expo-server-sdk</artifactId>
     <version>0.5.4</version>
     </dependency>

**Comment by jav** [comment]
I have only ever tried it with Java 11.
Could that be the problem?

**Comment by emmanuel-D** [comment]
Yes, I think that is the problem.
Is it possible to get your Library in **Java 1.8** , because I mean many projects are still running nowadays on **Java 1.8 in Production**?

**Comment by jav** [comment]
I'd gladly merge pullrequest to patch it to run Java 1.8.

Or, if you manage do point out the necessary changes, I could make them.

However, at this moment (and at least the next few days) don't have the bandwith to explore and discover what changes would be necessary to enable java 1.8.

**Comment by emmanuel-D** [comment]
I can clone your project & try to make it run on Java 1.8 on my side.
If it works as expected, then I will submit the Pull Request 😉

**Comment by jav** [comment]
As far as I can tell, the problem is that I'm using `java.net.http`.
All usage of `HttpClient`, `HttpResponse` and `HttpRequest` would have to be migrated to use the [java 8 HTTP Client API](https://docs.oracle.com/javame/8.0/api/httpclient/api/index.html).

(that, and changing `pom.xml` to use java 8)

**Comment by emmanuel-D** [comment]
Yes indeed.
But it not so easy with the old `java.net.*` libraries 😅 
I'm not sure I can accomplish that in the short term.

**Comment by jav** [comment]
Try out [version 0.6.0
](https://search.maven.org/artifact/io.github.jav/expo-server-sdk/0.6.0/jar)I've refactored it to use java.net.HttpUrlConnection .
I've tried it with java8 to the best of my abilities.

I've changed some interfaces (removed deprecated constructors), so I bumped the "major" version (assuming that, for major version '0', using the minor-version number norm where or backwards compatibility breaking changes change the minor-version)

**Comment by emmanuel-D** [comment]
@jav Great job. 
I have tried it on my own way, but the outcome was not working properly.😕
Then I installed your new Version 6.0 and all work perfect good on Java 8. 
Thanks once more 👍

**Comment by jav** [comment]
You're welcome!
