### ISSUE TITLE
ExpoPushMessage not equal to the same ExpoPushMessage

### ISSUE THREAD

**Issue by Bryksin** [jav/expo-server-sdk-java#6]
Hi

Had to build a `Map<ExpoPushMessage, SomeOtherStuff>` 
and unfortunately, realised that `mymap.get(expoPushMessage)` is null
Because `mymap.get(expoPushMessage) == expoPushMessage` is false
or 
`mymap.get(expoPushMessage).equals(expoPushMessage)` is also false

I would imagine `ExpoPushMessage` need to implement `equals()` and `hashcode()`

aditionally would be very nice if you would implement nice `toString()`, so if you print ExpoPushMessage or ExpoPushTicket it will print nicely, instead of going through each getter manually.

**Comment by jav** [comment]
Done
https://github.com/jav/expo-server-sdk-java/pull/8

ExpoPushMessage, ExpoPushTicket and ExpoPushReceipt now all implement hashCode() and equals().
